config/routes.rb
Blog::Application.routes.draw do

  resources :posts, :only => [:index, :new, :create, :show, :destroy] do
    resources :comm, :only => [:new, :create]
  end
  

  root :to => 'posts#index'

end

app/models/comm.rb
class Comm < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comms
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comm_controller.rb
# -*- coding: utf-8 -*-
class CommController < ApplicationController
  def new
    respond_to do |format|
      format.js
      format.html # pour faire passer le test…
    end
  end
  
  def create
    Comm.create(:nick => params[:n], :body => params[:b], :post_id => params[:post_id])
    redirect_to ["/posts/",params[:post_id]].join
  end
end

app/controllers/posts_controller.rb
# -*- coding: utf-8 -*-
class PostsController < ApplicationController
  
  def index
    @posts = Post.all
    if params[:auth]
      session[:conn] = 1
      params[:auth] = nil
    end
    if params[:disc]
      session[:conn] = nil
      params[:disc] = nil
    end
    @session = session[:conn]
  end
  
  def new
    if session[:conn]
      @posts = Post.all
      respond_to do |format|
        format.html # new.html.erb
        format.js
      end
    else
      redirect_to posts_url
    end
  end
  
  def create
    if session[:conn]
      Post.create(:title => params[:t], :body => params[:b])
      flash[:notice] = "Post " + params[:t] + " crée"
      redirect_to :posts
    else
      redirect_to posts_url
    end
  end
  
  def show
    @post = Post.find params[:id]
    @comm = Comm.find_all_by_post_id(@post)
    respond_to do |format|
      format.js
      format.html
    end
  end

  def destroy
    if session[:conn]
      flash[:notice] = "Post " + params[:id] + " supprimé"
      Post.find_by_id(params[:id]).delete
      Comm.find_all_by_post_id(params[:id]).each {|c| c.delete}
      @posts = Post.all
      @session = session[:conn]
      respond_to do |format|
        format.js
        format.html # pour le test…
      end
    else
      redirect_to posts_url
    end  
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comm/_new.html.erb
<%= form_tag(post_comm_index_path, :method => "post", :remote => true) do %>
  <%= label_tag(:n, "Nickname") %>
  <%= text_field_tag(:n) %>
  <%= label_tag(:b, "Comment") %>
  <%= text_field_tag(:b) %>
  <%= submit_tag("Debate") %>
<% end %>

app/views/comm/new.html.erb
<%= render 'new'%>

app/views/comm/new.js.erb
$("#new_comment").replaceWith("<%= escape_javascript(render 'new') %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag "style" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<h1><%= link_to  "My lovely blog", :root, :remote => false %></h1>
<p class="conn">
<% if @session %>
<%= link_to "Disconnect", "/posts?disc=1"  %>
<% else %>
<a href="http://localhost:4567/blog/session/new?origin="> Connect </a>
<% end %>
</p>

<%= yield %>

</body>
</html>

app/views/posts/_index.html.erb
<div id="content">
  <% if @session %>
  <%= link_to 'New', "posts/new", :remote => true%>
  <% end %>
  <% if flash[:notice] %>
  <p class="notice"><%= flash[:notice] %></p>
  <% end %>
  <ul>  
    <% @posts.each do |post| %> 
    <li><%= link_to post.title,  post, :remote => true %> 
      <% if @session %>
      <small><%= link_to "Delete", post, :method => :delete, :remote => true %></small>
      <% end %>
      <br/> 
      <%= post.body[0..200] %>… </li>
    <% end %>
  </ul>
</div>

app/views/posts/_new.html.erb
<div id="content">
<%= form_tag("/posts", :method => "post", :remote => true) do %>
  <%= label_tag(:t, "Title") %>
  <br/>
  <%= text_field_tag(:t) %>
  <br/>
  <%= label_tag(:b, "Body") %>
  <br/>
  <%= text_area_tag(:b) %>
  <br/>
  <%= submit_tag("Post") %>
<% end %>
<div>

app/views/posts/_show.html.erb
<div id="content">
  <%= link_to "Home",  :root, :remote => true %>
  <h2><%= @post.title %></h2>
  <p><%= @post.body %></p>
  <h2>Comments :</h2>
  <ul>  
    <% @comm.each do |c| %> 
    <li>
      <%= c.nick%>
      <br/>
      <%= c.body %>
    </li>
    <% end %>
  </ul>
  <%= link_to "Add comment", ["/posts/",@post.id,"/comm/new"].join, :remote => true, :id => :new_comment%>



<div>

app/views/posts/destroy.html.erb
<%= render 'index'%>

app/views/posts/destroy.js.erb
$("#content").replaceWith("<%= escape_javascript(render 'index') %>");

app/views/posts/index.html.erb
<%= render 'index'%>

app/views/posts/index.js.erb
$("#content").replaceWith("<%= escape_javascript(render 'index') %>");

app/views/posts/new.html.erb
<%= render 'new'%>

app/views/posts/new.js.erb
$("#content").replaceWith("<%= escape_javascript(render 'new') %>");

app/views/posts/show.html.erb
<%= render 'show'%>

app/views/posts/show.js.erb
$("#content").replaceWith("<%= escape_javascript(render 'show') %>");